#config_version=6

modes:
- pit # <- base mode
- green_flag # <- main mode
- backfire # <- hurry up beginning a pit stop
- grooveline # multiball 1
- luxury # multiball 2
- grand_prix # multiball 3
- red_line # <- wizard mode
- pure_evil # mode the player will not like
- high_score
- bonus
- match
- tilt
- segment_display
