#config_version=6

slides:
  dspc_animation_slide:
  - widget: dspc_animation
  splash_slide:
  - widget: splash
  - widget: champ_label
  - widget: champ_value
  - widget: first_place
  - widget: second_place
  - widget: third_place
  - widget: laps_champ_label
  - widget: laps_champ_value
  pit_slide:
  - widget: pit_background
  - widget: pit_mirror
  - widget: rear_view
  - widget: fuel_(current_player.level_fuel)
  - widget: lube_(current_player.level_lube)
  - widget: tires_(current_player.level_tires)
  - widget: laps_key
  - widget: laps_value
  - widget: ball_key
  - widget: ball_value
  - widget: driver_name
  green_flag_slide:
  - widget: green_flag_background
  - widget: green_flag_mirror
  - widget: rear_view
  - widget: fuel_(current_player.level_fuel)
  - widget: lube_(current_player.level_lube)
  - widget: tires_(current_player.level_tires)
  - widget: laps_key
  - widget: laps_value
  - widget: ball_key
  - widget: ball_value
  - widget: driver_name
  luxury_slide:
  - widget: luxury
  grooveline_slide:
  - widget: grooveline
  grand_prix_slide:
  - widget: grand_prix
  backfire_slide:
  - widget: backfire
