#config_version=6

widgets:
  splash:
  - type: image
    image: splash
    z: 0
  pit_background:
  - type: image
    image: pit-background
    z: 0
  pit_mirror:
  - type: image
    image: pit-mirror
    z: 1
  green_flag_background:
  - type: image
    image: green-flag-background
    z: 0
  green_flag_mirror:
  - type: image
    image: green-flag-mirror
    z: 1
  rear_view:
  - type: image
    image: rear-view
    z: 2
  grooveline:
  - type: image
    image: grooveline
  luxury:
  - type: image
    image: luxury
  backfire:
  - type: image
    image: backfire
  grand_prix:
  - type: image
    image: grand-prix
  lube_2:
  - type: image
    image: lube-2
    z: 3
    x: 9%
    y: 86%
  lube_1:
  - type: image
    image: lube-1
    z: 3
    x: 9%
    y: 86%
  lube_0:
  - type: image
    image: lube-0
    z: 3
    x: 9%
    y: 86%
  tires_2:
  - type: image
    image: tires-2
    z: 4
    x: 30%
    y: 57%
  tires_1:
  - type: image
    image: tires-1
    z: 4
    x: 30%
    y: 57%
  tires_0:
  - type: image
    image: tires-0
    z: 4
    x: 30%
    y: 57%
  fuel_2:
  - type: image
    image: fuel-2
    z: 5
    x: 12%
    y: 14%
  fuel_1:
  - type: image
    image: fuel-1
    z: 5
    x: 12%
    y: 14%
  fuel_0:
  - type: image
    image: fuel-0
    z: 5
    x: 12%
    y: 14%
  dspc_animation:
  - type: video
    video: dspc-animation
    width: 800
    height: 480
  laps_key:
  - type: text
    text: "Laps:"
    x: 64%
    y: 16%
    z: 5
    color: pink
    font_size: 28
  laps_value:
  - type: text
    text: "(lap_count)"
    z: 5
    x: 70%
    y: 16.2%
    color: pink
    style: medium
    font_size: 20
  ball_key:
  - type: text
    text: "Ball:"
    x: 64%
    y: 8.8%
    z: 5
    color: white
    font_size: 28
  ball_value:
  - type: text
    text: "(ball)"
    z: 5
    x: 70%
    y: 9%
    color: white
    style: medium
    font_size: 20
  driver_name:
  - type: text
    text: "(name)"
    x: 54.5%
    y: 9.5%
    z: 6
    color: cyan
    font_size: 42
  match_none:
  - type: image
    image: match-none
    z: 10
  match_00:
  - type: image
    image: match-00
    z: 10
  match_10:
  - type: image
    image: match-10
    z: 10
  match_20:
  - type: image
    image: match-20
    z: 10
  match_30:
  - type: image
    image: match-30
    z: 10
  match_40:
  - type: image
    image: match-40
    z: 10
  match_50:
  - type: image
    image: match-50
    z: 10
  match_60:
  - type: image
    image: match-60
    z: 10
  match_70:
  - type: image
    image: match-70
    z: 10
  match_80:
  - type: image
    image: match-80
    z: 10
  match_90:
  - type: image
    image: match-90
    z: 10
  match_text:
  - type: text
    text: "00"
    min_digits: 2
    x: center
    y: bottom+15%
    style: big
    color: cyan
    font_size: 150
    z: 10
  champ_label:
  - type: text
    text: "Grand Champion"
    anchor_x: left
    z: 2
    x: 5%
    y: bottom+92%
    color: cyan
    style: text_default
    font_size: 60
  champ_value:
  - type: text
    text: "(machine|score1_name): (machine|score1_value)"
    anchor_x: left
    z: 2
    x: 5%
    y: bottom+78%
    color: white
    style: big
    font_size: 40
  first_place:
  - type: text
    text: "1st: (machine|score2_name) ((machine|score2_value))"
    anchor_x: left
    z: 2
    x: 5%
    y: bottom+69%
    color: white
    style: medium
    font_size: 28
  second_place:
  - type: text
    text: "2nd: (machine|score3_name) ((machine|score3_value))"
    anchor_x: left
    z: 2
    x: 5%
    y: bottom+62%
    color: white
    style: medium
    font_size: 28
  third_place:
  - type: text
    text: "3rd: (machine|score4_name) ((machine|score4_value))"
    anchor_x: left
    z: 2
    x: 5%
    y: bottom+55%
    color: white
    style: medium
    font_size: 28
  laps_champ_label:
  - type: text
    text: "Laps Champ"
    anchor_x: left
    z: 2
    x: 2%
    y: bottom+10%
    color: pink
    style: big
    font_size: 20
  laps_champ_value:
  - type: text
    text: "(machine|lap_count1_name): (machine|lap_count1_value) Laps"
    anchor_x: left
    z: 2
    x: 2%
    y: bottom+4%
    color: white
    style: medium
    font_size: 18
